### ISSUE TITLE
Need way to install auth_proxy to run on a different port

### ISSUE THREAD

**Issue by dojacobs** [contiv/auth_proxy#110]
auth_proxy runs on port 10000. 

Problem is, my corporate network (aka. Cisco Lab) blocks port 10000.  This makes it rather difficult to get to the Contiv GUI  with a web browser.

Instead I'd like to use a more standard port, such as 443.

The work around I was given was to modify install/ansible/env.json and insert the following entry:
"auth_proxy_port" : "443"

Then run the installer as normal.

However when auth_proxy comes up, it's still on port 10000.  I verified this by using my Mac (on Blizzard, not Cisco Lab) to load the webpage.

Here is my modified env.json:

```json
{
  "auth_proxy_port":"443",  "docker_version":"1.12.6",
  "aci_gw_image":"contiv/aci-gw:latest",
  "contiv_network_version":"v1.0.0-alpha-01-28-2017.10-23-11.UTC",
  "env":{ "http_proxy":"", "HTTP_PROXY":"", "https_proxy":"", "no_proxy":",127.0.0.1,localhost,netmaster" },
  "etcd_peers_group": "netplugin-master",
  "service_vip": "172.31.6.66",
  "validate_certs": "no",
  "cluster_store": "etcd://54.219.167.152:2379",
  "auth_proxy_image": "contiv/auth_proxy:1.0.0-beta.2",
  "docker_reset_container_state": __RESET__,
  "docker_reset_image_state": __RESET_IMAGES__,
  "etcd_cleanup_state": __RESET__,
  "auth_proxy_local_install": False,
  "contiv_network_local_install": False
}
```

The original env.json isn't a valid json file, so my script simply opens this as a text file, and inserts the new entry at the top.

**Comment by dojacobs** [comment]
Added @stacykor because I'm sure customers will want to run auth_proxy on a different port for the same reason that I need to.

**Comment by dseevr** [comment]
@dojacobs could you copy-n-paste this issue over to the install repo?  As mentioned earlier, this isn't an auth_proxy bug and the `--listen-address` option is indeed working properly
